# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.11
_src_path: gh:algorandfoundation/algokit-python-template
author_email: yoongdoo0819@gmail.com
author_name: yoongdoo0819
contract_name: gend_contract
deployment_language: python
preset_name: starter
project_name: Gend-contracts

