export const myGenImages = [
  {
    id: 1,
    src: "https://via.placeholder.com/150",
    stats: {
      color: "black",
      size: "150x150",
      intelligence: 0.5,
      active: 0.5,
      emotion: 0.5,
      sensitive: 0.5,
    },
    priceRatio: [30, 20, 50, 10],
  },
  {
    id: 2,
    src: "https://via.placeholder.com/150",
    stats: {
      color: "black",
      size: "150x150",
      intelligence: 0.5,
      active: 0.5,
      emotion: 0.5,
      sensitive: 0.5,
    },
    priceRatio: [30, 20, 50],
  },
  {
    id: 3,
    src: "https://via.placeholder.com/150",
    stats: {
      color: "black",
      size: "150x150",
      intelligence: 0.5,
      active: 0.5,
      emotion: 0.5,
      sensitive: 0.5,
    },
  },
  {
    id: 4,
    src: "https://via.placeholder.com/150",
    stats: {
      color: "black",
      size: "150x150",
      intelligence: 0.5,
      active: 0.5,
      emotion: 0.5,
      sensitive: 0.5,
    },
  },
  {
    id: 5,
    src: "https://via.placeholder.com/150",
    stats: {
      color: "black",
      size: "150x150",
      intelligence: 0.5,
      active: 0.5,
      emotion: 0.5,
      sensitive: 0.5,
    },
  },
  {
    id: 6,
    src: "https://via.placeholder.com/150",
    stats: {
      color: "black",
      size: "150x150",
      intelligence: 0.5,
      active: 0.5,
      emotion: 0.5,
      sensitive: 0.5,
    },
  },
  {
    id: 7,
    src: "https://via.placeholder.com/150",
    stats: {
      color: "black",
      size: "150x150",
      intelligence: 0.5,
      active: 0.5,
      emotion: 0.5,
      sensitive: 0.5,
    },
  },
  {
    id: 8,
    src: "https://via.placeholder.com/150",
    stats: {
      color: "black",
      size: "150x150",
      intelligence: 0.5,
      active: 0.5,
      emotion: 0.5,
      sensitive: 0.5,
    },
  },
];
